### ISSUE TITLE
Can you read a Lua function by name?

### ISSUE THREAD

**Issue by Dismalitie** [AnnulusGames/Lua-CSharp#55]
Hi, I was reading the section on [calling Lua functions from C#](https://github.com/AnnulusGames/Lua-CSharp?tab=readme-ov-file#calling-lua-functions-from-c) and saw that the example code showed reading the function from the result table by index. Is there a way to read the function by name? Say if I had a function called `Init()` in Lua, would I be able to read that specific function by doing something like this?
```cs
var results = await state.DoFileAsync("example.lua");
var func = results["init"].Read<LuaFunction>();

var funcResults = await func.InvokeAsync(state, new[] { "GE_Graph_Athena01" });
```

**Comment by AnnulusGames** [comment]
Sorry, but I can't really understand what you want to achieve from just the C# code. Could you please post the code for `example.lua`?

**Comment by Dismalitie** [comment]
```lua
function init()
    -- ...
end

return init
```

**Comment by AnnulusGames** [comment]
If you want to access global variables, you don't need to return a function from the Lua side. You can get it with state.Environment["init"].

**Comment by Dismalitie** [comment]
Oh thanks! I should've thought of that since you can access variables via that method.
